POST https://flutter-myshop-ct484-d15fa-default-rtdb.asia-southeast1.firebasedatabase.app/products.json?
Content-Type: application/json

{
"creatorId": "cy9uecJW3ugBqw0MnwBuE97U44F3",
"description": "Handmade hug pillows are chosen by many girls to give to their boyfriends. Simply two pieces of fabric, needles, plushies and a little talent for embroidery create a personalized hug pillow.",
"imageUrl": "https://blogger.googleusercontent.com/img/a/AVvXsEhaEJdz27Atm80qJAzA0XvuO5TEewsL-HCHqxIMzKdFIIhKL7PDwFyS3RWb1d8R3lzzrPf7xuxEvwUrOrD7VMaIQIsJYBIBNQORWONYmEgtsoKbPGt8mXJClntfGvq_uZjUgC4n9YU5z1M9ihB7b7Xv1_y1i8_a3HQ6VIi-wYme5ayPcFCzX01kNcf3Rg=s512",
"price": 30.09,
"title": "Love pack"
}

###
GET https://flutter-myshop-ct484-d15fa-default-rtdb.asia-southeast1.firebasedatabase.app/products/-NHJSLP20I0zwjl3HTkh.json?

###
GET https://flutter-myshop-ct484-d15fa-default-rtdb.asia-southeast1.firebasedatabase.app/userFavorites/cy9uecJW3ugBqw0MnwBuE97U44F3.json?

{
    "-NHJSLP20I0zwjl3HTkh": false,
    "-NHJTBbm6fDCbrn0LfiK": true
}